from fastapi import FastAPI

app = FastAPI()


@app.get("/")
async def root():
    return {"message": "Hello World"}


@app.get("/hello/{name}")
async def say_hello(name: str):
    return {"message": f"Hello {name}"}

@app.post("/toolformer/{prompt}")
async def toolformer():
    return {"message": "This is the string generated by the toolformer model."}